[project]
name = "bootdotdev-rag"
version = "0.1.0"
description = "A project for bootdotdev to practice RAG"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nltk==3.9.1",
    "numpy>=2.3.4",
    "sentence-transformers>=5.1.2",
]
